name: Test
on:
  push:
    branches:
       - '**'  
  pull_request:
    branches:
       - '**'  

jobs:
  build:
   runs-on: ubuntu-20.04
  
   steps:
     - uses: actions/checkout@v3
     - name: Build Docker image 
       run: docker build -t test .
     - name: Run tests inside the container
       run: docker run test poetry run pytest
