name: MLLINT

on:
  push:
    branches:
       - '**'  
  pull_request:
    branches:
       - '**'  

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3
      - uses: cclauss/GitHub-Action-for-pylint@0.7.0

      #Setup python
      - name: Setup Python
        uses: actions/setup-python@v3.1.2
        with:
          python-version: 3.8
    
      - name: Dependencies
        run: pip install mypy
        
      #Run mypy
      - name: Run Mypy
        run: mypy --strict $(git ls-files '*.py')
      
      #Run Isort (Check import order)
      - name: python-isort
        uses: isort/isort-action@v0.1.0
      
      #Run bandit
      - name: Python security check using Bandit
        uses: Joel-hanson/bandit-report-artifacts@V1
    
      #Run pylint
      - name: GitHub Action for pylint
        run: pip install -r requirements.txt ; pylint **/*.py
  
      # Runs a single command using the runners shell
      - name: Run MLLINT
        run: docker run --rm -v ${{ github.workspace }}:/app bvobart/mllint:latest



