name: MLLINT

on:
  push:
    branches:
       - '**'  
  pull_request:
    branches:
       - '**'  

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3
      
      #Setup python
      - name: Setup Python
        uses: actions/setup-python@v3.1.2
        with:
          python-version: 3.x
    
      - name: Dependencies
        run: pip install mypy
        
      #Run mypy
      - name: Run Mypy
        run: mypy --strict $(git ls-files '*.py')
      
      #Run Isort (Check import order)
      - uses: jamescurtin/isort-action@master
        with:
            requirementsFiles: "requirements.txt requirements-test.txt"
            
      # Runs a single command using the runners shell
      - name: Run MLLINT
        run: docker run --rm -v ${{ github.workspace }}:/app bvobart/mllint:latest



