name: MLLINT

on:
  push:
    branches:
       - '**'  
  pull_request:
    branches:
       - '**'  

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3

      # Runs a single command using the runners shell
      - name: Run MLLINT
        run: docker run -it --rm -v ${{ github.workspace }}:/app bvobart/mllint:latest



