name: StaticAnalysis

on:
  push:
    branches:
       - '**'  
  pull_request:
    branches:
       - '**'  

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3
      - uses: cclauss/GitHub-Action-for-pylint@0.7.0

      #Setup python
      - name: Setup Python
        uses: actions/setup-python@v3.1.2
        with:
          python-version: 3.8
    
      - name: Dependencies
        run: |
          pip install mypy
          pip install pylint

      #Run black
      - name: Run Black
        uses: psf/black@stable
        
      #Run mypy
      - name: Run Mypy
        run: mypy $(git ls-files '*.py')
      
      #Run Isort (Check import order)
      - name: python-isort
        uses: isort/isort-action@v0.1.0
      
      #Run bandit
      - name: Python security check using Bandit
        uses: Joel-hanson/bandit-report-artifacts@V1
    
      #Run pylint
      - name: GitHub Action for pylint
        run: pylint $(git ls-files '*.py')
      
      #Publish the bandit output as an artifact
      - uses: actions/upload-artifact@v3
        if: always()
        with:
          name: Bandit security report
          path: |
            output/security_report.txt
        
      # Runs a single command using the runners shell
      # - name: Run MLLINT
      # run: docker run --rm -v ${{ github.workspace }}:/app bvobart/mllint:latest



