name: Train Model

on:
  schedule:
    # * is a special character in YAML so you have to quote this string
    - cron:  '40 15 * * *'


jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3

      #Setup python
      - name: Setup Python
        uses: actions/setup-python@v3.1.2
        with:
          python-version: 3.8
    
      - name: Dependencies
        run: |
          pip install -r requirements.txt

      
      #Run pylint
      - name: Train model
        run: |
          gdown --folder https://drive.google.com/drive/folders/1D5wxqjiL1OiVL7EZXLY9YvkAXqlTtj2d?usp=sharing
          gdown -O data/online.tsv https://docs.google.com/spreadsheets/d/1XeQkfdNCQB8L1EmwSEzgMeOSq3bXoKBh9JN337UGhSI/export?format=tsv
          mkdir model
          python so_classifier/train_model.py
        
      # Runs a single command using the runners shell
      # - name: Run MLLINT
      # run: docker run --rm -v ${{ github.workspace }}:/app bvobart/mllint:latest



